[package]
name = "awakefl"
version = "0.1.0"
description = "AwakeFL - camada de reputacao on-chain para Federated Learning"
edition = "2021"

[lib]
crate-type = ["cdylib", "lib"]
name = "awakefl"

[features]
default = []
cpi = ["no-entrypoint"]
no-entrypoint = []
no-idl = []
no-log-ix-name = []
idl-build = ["anchor-lang/idl-build"]

[dependencies]
anchor-lang = "0.31.1"
